import { Inter } from "next/font/google";
import "./globals.css";

import Header from "./_components/Header/Header";
import SideNav from "./_components/SideNav/SideNav";
import SessionWrapper from "@/SessionWrapper";
import ClientProvider from "./_components/ClientProvider/ClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "OpenSpace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <GoogleOAuthProvider clientId={process.env.GOOGLE_CLIENT_ID}> */}
        <ClientProvider>
        <Header />
        <div className="h-[100%] flex justify-between ">
          <div className="w-[5%]">
            <SideNav />
          </div>
          <div className="w-[95%]">
            <SessionWrapper>{children}</SessionWrapper>
          </div>
        </div>
        </ClientProvider>
        {/* </GoogleOAuthProvider> */}
      </body>
    </html>
  );
}
